[package]
name = "monotronian"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2018"

[dependencies.nom]
version = "4.0"
default_features = false

[dependencies]
heapless = "*"
